// This file represents EF Core migration commands to run.
// Run these from the backend/ directory:
//
//   dotnet ef migrations add InitialCreate
//   dotnet ef database update
//
// Or use the schema.sql file directly in docs/schema.sql
//
// The migration snapshot is auto-generated by EF Core tools.
// Below is the conceptual migration for reference.

/*
 MIGRATION: InitialCreate
 
 Tables created:
   - users
   - vegetables
   - order_items
   - orders
 
 Indexes:
   - users.email (unique)
   - vegetables.category, is_active, is_featured, price
   - orders.user_id, status, created_at
   - order_items.order_id
 
 Seed data:
   - Admin user (admin@veggio.io / Admin@123)
   - 10 sample vegetables
*/
